### ISSUE TITLE
QUASAR always picks 1st stream

### ISSUE THREAD

**Issue by dtsexpert** [metate/meta4kodi#1]
Works great with Qauasar. Althought disabling the auto play in Quasar setting, it always plays 1st stream available. Any chance we have the quasar stream dialog popup for stream selection?
Once again thanks for great addon.

**Comment by metate** [comment]
Player updated to respect the autoplay setting.

As an alternative a separate player could have been added to always bring up the stream selection dialog. If anyone wants to write his own player for Quasar then these are the links to use that override the quasar setting:

Always play:
Movies: plugin://plugin.video.quasar/movie/{tmdb}/play
TV: plugin://plugin.video.quasar/show/{tmdb}/season/{season}/episode/{episode}/play

Always show stream selection:
Movies: plugin://plugin.video.quasar/movie/{tmdb}/links
TV: plugin://plugin.video.quasar/show/{tmdb}/season/{season}/episode/{episode}/links
