### ISSUE TITLE
Adding Movie to Library issue - incorrect date added label

### ISSUE THREAD

**Issue by chiefkes** [metate/meta4kodi#10]
If I add a movie to the library with Meta it doesn't appear at all in the default kodi "recently added movies" playlist. It does, however, appear in a custom smart playlist that i've created called "unwatched movies" (play count is 0, sorted by date added (descending)), but right at the end when it should appear at the beginning as the most recently added movie. Movies added to the library with other video add-ons appear correctly in both the "recently added movies" and at the beginning of "unwatched movies".

Recently added episodes seem to work fine.

Can provide a log if useful.

**Comment by metate** [comment]
Meta change the strm file date to the movie release date (easier sorting by date for me personally). If that isn't the wanted behavior I would disable it by default and set it as an advanced setting.

**Comment by chiefkes** [comment]
Isn't the movie release date scraped anyway? It's already possible to access your movie library sorted via movie release date by changing the sort order of the movies playlist. However, changing the strm file date means that it's no longer possible to have a list sorted by the date that you added a movie strm to your library. Correct me if I'm wrong. Also it means that meta library items are behaving in a different manner, in terms of date ordering, to other video add-on library items.

**Comment by metate** [comment]
IIRC Kodi only allows sorting by year, not full date. That being said I accept your request and will change this behavior in the next update.

**Comment by chiefkes** [comment]
Thankyou, much appreciated!

**Comment by chiefkes** [comment]
Perhaps an option in meta's 'library' settings to change between date added and full release?
