### ISSUE TITLE
Import from Trakt

### ISSUE THREAD

**Issue by NunoFilipeSantos** [metate/meta4kodi#2]
Would it be possible to import media from Takt lists on an scheduled interval?

**Comment by mhancoc7** [comment]
I think it would be better to just have trakt authorization so that there could be two new sections.

My Movie Collection
My TV Show Collection

These would both be pulled from the trakt account.

**Comment by NunoFilipeSantos** [comment]
That would be a possibility but it would defeat the purpose of Kodi's library integration.

**Comment by mhancoc7** [comment]
I don't see it as defeating the purpose of anything. It would allow Meta to be a truly portable way to setup different kodi systems all with the same media more simply. Since this addon is very much geared towards the use of addons it seems that trakt integration is an obvious addition.

**Comment by NunoFilipeSantos** [comment]
I was referring to one of the stated purposes of the addon: 

> Add media content to local library

**Comment by chiefkes** [comment]
@jeremehancock You're essentially making a different feature request. NunoFilipeSantos's request is for the meta dev to provide the ability to import trakt lists via meta into the native kodi library, whereas you are asking for personal trakt lists to be available from within the meta add-on itself. Both potentially very useful ideas, but I think that your use of the word "better" implies that you don't quite understand what NunoFilipeSantos is requesting.

**Comment by NunoFilipeSantos** [comment]
Exactly @chiefkes, that is the point of my enhancement request.

**Comment by mhancoc7** [comment]
Sorry if I was missing the point of the request. I think both features would be awesome! I love where this addon is going by the way. I will put in a request for the trakt integration. Thanks guys

**Comment by ghost** [comment]
it's not exactly what you want, but the trakt code i'm working on has add all to library buttons for collections/watchlists

**Comment by metate** [comment]
This will be implemented when https://github.com/metate/meta4kodi/issues/16 and https://github.com/metate/meta4kodi/issues/22 are done so I'm closing this issue for better issue traking. Thanks.
