### ISSUE TITLE
Add feature to allow keyword injection into search

### ISSUE THREAD

**Issue by spoyser** [metate/meta4kodi#21]
Would it be possible to add a feature to allow keywords to be "injected" into the search, eg using the following syntax to search for Super Man

`RunPlugin("plugin://plugin.video.meta/movies/search=Super%20Man")`

(keywords url encoded to simplify things)

This would then bypass any selection or keyboard entry and automatically search for Super Man

This would be very useful as I could then add Meta to the iSearch feature of my Super Favourites addon.

**Comment by metate** [comment]
Try
`/movies/search_term/<term>/<page>`

where term is super man and page is set to 1 (for the first page of results).

**Comment by spoyser** [comment]
Cheers for that, will give it a whirl

Now tested and it works a treat :+1: 

Nice work on the addon by the way.
