### ISSUE TITLE
context.meta crash

### ISSUE THREAD

**Issue by chiefkes** [metate/meta4kodi#3]
1) No error is returned when the tv show "vikings" is launched via the integrated meta addon search.
2) Error returned with the TV show 'vikings' when meta is launched using the context menu on a library entry populated by a different video addon.  
3) Adding 'vikings' to library from meta and launching this causes Kodi to freeze, requiring a force close.

Log.old: http://xbmclogs.com/pnkwm0jic

4)Upon relaunch meta library entry does work, but "select stream" from a a library entry populated by a different video addon still doesn't work.

log: http://xbmclogs.com/pfwihgyrq

**Comment by chiefkes** [comment]
The same issue exists for quite a few other tv shows. Attached is another log with a mixture of success and meta errors

http://xbmclogs.com/pnucubrd3

**Comment by metate** [comment]
Confirmed as a bug in context.meta, thanks.
