### ISSUE TITLE
Meta-Context-Menu won't display the string as needed

### ISSUE THREAD

**Issue by ygoldgold** [metate/meta4kodi#45]
in context.meta  -    addon.xml  is pointing to wrong string.
The result is that you cannot see anything in the context menu (but it is there)

This is the right string number
        <label>$ADDON[plugin.video.meta 30602]</label>

**Comment by itzikg** [comment]
@ygoldgold 
Make sure you are on context.meta Version 1.0.2
This string 30602("Select stream") is there

**Comment by itzikg** [comment]
@ygoldgold 
 Thanks It has been updated in the next version.
