### ISSUE TITLE
"PLAYER REQUEST"

### ISSUE THREAD

**Issue by w00dy1981** [metate/meta4kodi#49]
Hi,

I would like to make a request for some players for Meta

Could you please create players for all of Mucky Ducks add-ons?

I like using MOVIEFLIX, HD BOX and IMPERIAL STREAMS as a substitute to Exodus, SALTS or Specto and would love these to be included in the already included players

**Comment by metate** [comment]
No. No piracy talk here please.

**Comment by w00dy1981** [comment]
Sorry man didn't mean to or realise I was discussing anything pirate like.

So is there anyway to get anymore players to go along with the players currently provided?
