### ISSUE TITLE
Lazy TV issues

### ISSUE THREAD

**Issue by chiefkes** [metate/meta4kodi#5]
Tried launching meta generated library entries using Lazy TV. The meta add-on does display and populate correctly, but then nothing happens when an add-on is selected. Second attempt at doing this caused Kodi to crash.

Log: http://xbmclogs.com/ppo3hr60b

**Comment by metate** [comment]
That might be tricky, some of my recent changes probably broke it but were necessary for supporting more addons. Hope it can be bypasses. Thanks for the report.

**Comment by chiefkes** [comment]
Solved by switching the video add-on's source selection from 'dialog' to 'directory' mode.
