### ISSUE TITLE
Request unique api-keys

### ISSUE THREAD

**Issue by OpenELEQ** [metate/meta4kodi#56]
To avoid re-occurence of the api-issues experienced recently, could you please apply for your own, unique api-keys?
I would advise to do so for all the apis involved, thanks.
I am also going to add the option to use custom api-keys, maybe that would be a smart addition for you too?

**Comment by roee88** [comment]
I wasn't involved in the recent updates to Meta. I'll generate a new key of course. If you implement a custom key setting, a PR would be great. Thanks!

**Comment by roee88** [comment]
Resolved in last release
