### ISSUE TITLE
Re-attempted stream launch upon termination of stream

### ISSUE THREAD

**Issue by chiefkes** [metate/meta4kodi#6]
Certain video add-ons attempt a second play of streams after they've finished/stopped. This doesn't happen when played directly through the add-ons themselves.

Log: http://xbmclogs.com/pmqvwdzd1

**Comment by metate** [comment]
The log isn't readable. Please explain with more details and provide a (legal only) example if possible. Also, I think one of your installed scripts has a temporary bug making it play items from favorites/widgets on its own. Just to make sure that's not the case, is the video item marked as favorite? Is it listed in a home screen widget? Does it happen with other items (not favored or listed in widgets)?

**Comment by chiefkes** [comment]
I'm afraid I haven't been able to reproduce this behaviour with any add-ons other than those in the log, so it may well be an issue with the players themselves. Of course I understand that you are not able to provide support if this is the case, and I very much appreciate your time anyway.

As for the log I provided, I opened a number of streams via the library and also from within the meta add-on itself, selected the add-ons that are exhibiting this behaviour and chose a steam. I then ended the stream and at this point the add-on would attempt to open the stream again.

The video item is not marked as a favourite. It was listed in a home screen widget (using the fTV sualfred mod skin), however the re-launching does happen with other items not in my library or listed in widgets. It happens for all video items using those add-ons.

Again, please ignore this if it is clearly an issue with the unsupported add-ons and their players, but it might be a skin widgets script conflict or something similar in which case other supported add-ons might feasibly be affected

**Comment by metate** [comment]
Do you have a custom advancedsettings.xml in your kodi/userdata folder? Also, are you sure it's attempting to play the same exact item and not e.g. the next episode? (If that's the case, and again just to be sure, then verify Settings->Videos->Playback->Play next video automatically is off)

**Comment by chiefkes** [comment]
I don't have a custom advancedsettings.xml and yes it's the same episode that it's trying to play. Play next video automatically is off. Incidentally, i'm getting the same behaviour for movies as well. Also to be clear it's not so much a second attempt as it is continuous loop, but that's probably obvious. 

Just tried with confluence, and also disabling program, service and context menu add-ons one by one, and that didn't make any difference

**Comment by chiefkes** [comment]
Solved! Addons in question were listing a choice of streams to select in "dialog" mode. After switching to "directory" mode, the playback loop problem has disappeared. Not sure if that's of interest to meta, but thank you for your time and help
