### ISSUE TITLE
Meta-Context-Menu won't open selector

### ISSUE THREAD

**Issue by ygoldgold** [metate/meta4kodi#9]
my movies are nfs links to strm files, which point currently to Quasar.
(Kodi 16.    working with windows 7.  HaneWin is an NFS server installed on my windows desktop)

this is what happens when right clicking on a movie and choosing "play with..."
(I'm quite sure you don't need the full log)
(There is some problem translating my nfs link probably)

> 19:43:16 T:3240  NOTICE: Thread LanguageInvoker start, auto delete: false
> 19:43:16 T:3240  NOTICE: -->Python Interpreter Initialized<--
> 19:43:16 T:3240   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.IOError'>
>                                             Error Contents: (22, "invalid mode ('rb') or filename", 'nfs://192.168.1.10/media/data/moviesfeeder/ill see you in my dreams (2015)/ill see you in my dreams (2015).strm')
>                                             Traceback (most recent call last):
>                                               File "C:\Users\g\AppData\Roaming\Kodi\addons\context.meta\context_playable.py", line 97, in <module>
>                                                 main()
>                                               File "C:\Users\g\AppData\Roaming\Kodi\addons\context.meta\context_playable.py", line 49, in main
>                                                 url = get_url(stream_file)
>                                               File "C:\Users\g\AppData\Roaming\Kodi\addons\context.meta\context_playable.py", line 14, in get_url
>                                                 with open(xbmc.translatePath(stream_file), "rb") as f:
>                                             IOError: (22, "invalid mode ('rb') or filename", 'nfs://192.168.1.10/media/data/moviesfeeder/ill see you in my dreams (2015)/ill see you in my dreams (2015).strm')
>                                             -->End of Python script error report<--

**Comment by metate** [comment]
@ygoldgold does it work now?

**Comment by ygoldgold** [comment]
Works Perfectly !
Thank you !

**Comment by itzikg** [comment]
excellent
